### ISSUE TITLE
Feature: User can Search and it appears-1

### ISSUE THREAD

**Issue by GustavoAyala1** [GustavoAyala1/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for movies OR  tv shows and an image with tiltle will be brought up. Then they can save and comment on what they would like.

## 📐 Functionality

> User can search for their favorite movies and tv shows. Save them and leave comments on them to read later

## 🖼️ Wireframes

> 
![figma](https://user-images.githubusercontent.com/80282083/140839314-87a12285-945b-4818-9c6b-e6da4e4ef73a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] can search for movies and tv shows
         - [ ] Create a container below the Nav to hold movie/show results
         - [ ] setup form functionality to extract values from inputs and add to api search results
         - [ ] configure api search result to get desired/correct  results
- [x] found movies and tv shows show up 
         - [ ] they have their own image/title/date
         - [ ] a save button is also added to add comments and save them to collections
         - [ ] comment is added after being saved
