### ISSUE TITLE
Feature: User can save search results to home/collections page-2

### ISSUE THREAD

**Issue by GustavoAyala1** [GustavoAyala1/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add 'favorites' to the home page

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
A user clicks save to save it to the home page and adds a comment if they want.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![figma](https://user-images.githubusercontent.com/80282083/141205072-cce286c3-64c3-4b2e-a410-61d074e68f02.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] User can save their favorites to home page
- [x] After searching if they click on Collections they get sent back to home page
- [x] Home page is populated with entries they favorited
- [x] If they had a comment that is displayed aswel
