### ISSUE TITLE
Feature: User can sort results by data

### ISSUE THREAD

**Issue by GustavoAyala1** [GustavoAyala1/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can choose in what order the searched items appear.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Can select the sort menu and search items get sorted by year

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![figma](https://user-images.githubusercontent.com/80282083/141220233-43f135f2-a6c7-473d-9d7b-f16011e64e04.png)
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] can sort by Year 
- [ ] Either by newest or oldest
- [ ] and set it back to original order
