### ISSUE TITLE
Feature: User can have random videos in home page if nothing is saved

### ISSUE THREAD

**Issue by GustavoAyala1** [GustavoAyala1/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can arrive at a home page with random entries

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The home page will random entries and if they go back to home page after searching then home page will still have random entries

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/80282083/141385628-fe6b79aa-4be6-4be4-a762-18a1a00a55e5.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] If first time on page the Home/collections page has random entries
- [x] If going back to collections after a search and no entry was save then home page is still random
- [x] Comment will show up on home page after saving a comment
